# Generated by Django 3.0.2 on 2020-05-25 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_title', models.CharField(max_length=100)),
                ('payment_description', models.TextField()),
                ('payment_purpose', models.CharField(choices=[('Bill Payment', 'Bill Payment'), ('Personal Use', 'Personal Use'), ('Expenses', 'Expenses'), ('Salary', 'Salary'), ('Tax Payment', 'Tax Payment'), ('Others', 'Others')], default='Bill Payment', max_length=30)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
