# Generated by Django 3.0.2 on 2020-05-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_amount',
            field=models.IntegerField(default=0),
        ),
    ]
