# Generated by Django 3.0.2 on 2020-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('services_id', models.AutoField(primary_key=True, serialize=False)),
                ('services_title', models.CharField(max_length=50)),
                ('services_description', models.CharField(max_length=100)),
                ('services_contact', models.CharField(max_length=20)),
                ('services_img', models.CharField(max_length=100)),
            ],
        ),
    ]
